### PR TITLE
Refactor all nodes

### PR DESCRIPTION
**Pull request by knarkzel**
* [8/21] Tasks

- [X] base64
- [X] blake2b512
- [X] case_conversion
- [X] difference
- [X] math
- [X] md5
- [ ] multisort
- [X] number_sort
- [X] number_sort_rev
- [x] random
- [x] random_vec_u64
- [ ] regex
- [x] reverse
- [x] sha256
- [ ] sort
- [ ] supabase
- [ ] urls
- [ ] uuid
- [ ] weather
- [ ] word_sort
- [ ] word_sort_rev

### CODE REVIEW

**Comment by enzotar** [comment]
Multiple inputs not a single, right

**Comment by knarkzel** [comment]
I'm doing single, the wasm runtime expects a single input and returns a single output (better for serialization and deserialization). We can modify the node definitions so that they take multiple inputs, then we can merge them together in space-operator-flow/src/command/wasm.rs

**Comment by knarkzel** [comment]
So for the user it looks like they are multiple inputs, but it's really just one object with multiple fields.

**Comment by enzotar** [comment]
Got it

**Pull request merged**
